### ISSUE TITLE
Cannot Patch Break Arts Patched ISO

### ISSUE THREAD

**Issue by JStefanik9631** [GReinoso96/MH2Plus#5]
I cannot get this patch to work. I have a working patched english translation iso and cannot patch it with MH2Plus. All I am doing is trying to patch it using delta patcher. Are there any other steps? I have checked the MD5 and SHA-1 and know I am using the correct files, so I am beyond confused.

**Comment by NonHeroJC** [comment]
There is a workaround for this issue. When you go to apply the patch to the .iso, click the Settings Icon next to the "Apply Patch" button. The you need to uncheck Checksum Validation. This should bypass the error and allow it to install.

**Comment by JStefanik9631** [comment]
That worked! Thanks for the help!
